CREATE TABLE USER(
    username varchar(30),
    user_id varchar(15) primary key,
    email varchar(30),
    password varchar(20) NOT NULL,
    phno int
);
CREATE TABLE DESTINATION
(
    DESTINATION_ID INT AUTO_INCREMENT PRIMARY KEY,
    Dest_NAME VARCHAR(50),
    COUNTRY VARCHAR(20),
    DESCRIPTION TEXT,
    POPULARITY INT
);
CREATE TABLE FLIGHT(
    FLIGHT_ID INT AUTO_INCREMENT PRIMARY KEY,
    DEPARTURE_DATE DATE,
    RETURN_DATE DATE,
    DEPARTURE_TIME TIME, -- Added for departure time
    RETURN_TIME TIME,
    PRICE DECIMAL(10,2),
    AIRLINE VARCHAR(20),
    DESTINATION_ID INT,
    User_ID VARCHAR(15),
    FOREIGN KEY(USER_ID) REFERENCES USER(USER_ID),
    FOREIGN KEY (DESTINATION_ID) REFERENCES Destination(DESTINATION_ID)
);
CREATE TABLE ACCOMMODATION(
    ACCOMMODATION_ID INT AUTO_INCREMENT PRIMARY KEY,
    ACCOMODATION_NAME VARCHAR(30),
    PRICE_PER_NIGHT DECIMAL(10,2),
    AVAIL_ROOMS INT,
    DESTINATION_ID INT,
    FOREIGN KEY(DESTINATION_ID) REFERENCES DESTINATION(DESTINATION_ID)
);
CREATE TABLE AccommodationReservation(
    Reservation_ID INT AUTO_INCREMENT PRIMARY KEY,
    ACCOMMODATION_ID INT,
    USER_ID VARCHAR(15),
    NO_ROOMS INT,
    CHECK_IN_DATE DATE,
    CHECK_OUT_DATE DATE,
    FOREIGN KEY (ACCOMMODATION_ID) REFERENCES ACCOMMODATION(ACCOMMODATION_ID),
    FOREIGN KEY (USER_ID) REFERENCES USER(USER_ID)
);
CREATE TABLE Booking (
    Booking_ID INT AUTO_INCREMENT PRIMARY KEY,
    User_ID Varchar(15),
    Reservation_ID INT,
    Flight_ID INT,
    FROMDATE DATE,
    TODATE DATE,
    TotalPrice DECIMAL(10, 2),
    FOREIGN KEY (User_ID) REFERENCES User(User_id),
    FOREIGN KEY (Reservation_ID) REFERENCES AccommodationReservation(Reservation_ID),
    FOREIGN KEY (Flight_ID) REFERENCES Flight(Flight_ID)
);
